var poem = {
  'author': 'T.S. Eliot',
  'title':  'The Love Song of J. Alfred Prufrock',
  'text': 
  [
    {
      verse:  1,
      line:  1,
      length: 3,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Let us go then, you and I,',
    },
    {
      verse:  1,
      line:  2,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'When the evening is spread out against the sky',
    },
    {
      verse:  1,
      line:  3,
      length: 5,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Like a patient etherized upon a table;',
    },
    {
      verse:  1,
      line:  4,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Let us go, through certain half-deserted streets,',
    },
    {
      verse:  1,
      line:  5,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'The muttering retreats',
    },
    {
      verse:  1,
      line:  6,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Of restless nights in one-night cheap hotels',
    },
    {
      verse:  1,
      line:  7,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'And sawdust restaurants with oyster-shells:',
    },
    {
      verse:  1,
      line:  8,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Streets that follow like a tedious argument',
    },
    {
      verse:  1,
      line:  9,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Of insidious intent',
    },
    {
      verse:  1,
      line:  10,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'To lead you to an overwhelming question ...',
    },
    {
      verse:  1,
      line:  11,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Oh, do not ask, "What is it?',
    },
    {
      verse:  1,
      line:  12,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Let us go and make our visit.',
    },
    {
      verse:  2,
      line:  13,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'In the room the women come and go',
    },
    {
      verse:  2,
      line:  14,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   'Talking of Michelangelo.',
    },
    {
      verse:  3,
      line:  15,
      length: 1,
      enter:  'testEnter',
      exit:   'testExit',
      text:   '',
    }
  ]
};
